CREATE TABLE LANCAMENTO(
  CODLANC INT NOT NULL,
  CODFUN INT NOT NULL,
  CODLAN INT NOT NULL,
  CODACES INT NOT NULL,
  DTHR DATE NOT NULL,
  CONSTRAINT FK_FUNC FOREIGN KEY(CODFUN) REFERENCES FUNCIONARIO(CODFUN),
  CONSTRAINT FK_SET FOREIGN KEY(CODACES) REFERENCES SETOR(CODSET),
  CONSTRAINT FK_PONTO FOREIGN KEY(CODLAN) REFERENCES PONTOELETRONICO(CODPONT),
  CONSTRAINT PK_LANC PRIMARY KEY(CODLANC),
  CHECK (CODACES = 1)
);

CREATE TABLE PONTOELETRONICO(
  CODPONT INT NOT NULL,
  CONSTRAINT PK_PONTOELETRONICO PRIMARY KEY(CODPONT)
);

CREATE TABLE SETOR(
  CODSET INT NOT NULL,
  NOMSET VARCHAR(35) NOT NULL,
  CONSTRAINT PK_SETOR PRIMARY KEY(CODSET)
);


CREATE TABLE CARGO(
  CODCAR INT NOT NULL,
  DESCAR VARCHAR(35) NOT NULL,
  CONSTRAINT PK_CARGO PRIMARY KEY(CODCAR)
);

CREATE TABLE FUNCIONARIO(
  CODFUN INT NOT NULL,
  NOMFUN VARCHAR(35) NOT NULL,
  CPF VARCHAR(50) NOT NULL,
  RG VARCHAR(50) NOT NULL,
  DTNASC DATE,
  CODSET INT NOT NULL,
  CODCAR INT NOT NULL,
  CONSTRAINT PK_FUNCIONARIO PRIMARY KEY(CODFUN),
  CONSTRAINT FK_SETOR FOREIGN KEY(CODSET) REFERENCES SETOR(CODSET),
  CONSTRAINT FK_CODCAR FOREIGN KEY(CODCAR) REFERENCES CARGO(CODCAR)
);