SELECT DISTINCT NOMFUN,CODFUN,DTHR FROM FUNCIONARIO NATURAL JOIN LANCAMENTO WHERE TO_CHAR(DTHR,'DD/MM/YYYY') = TO_CHAR(SYSDATE,'DD/MM/YYYY')
SELECT DISTINCT COUNT(CODFUN) FROM FUNCIONARIO WHERE CODFUN NOT IN(SELECT CODFUN FROM LANCAMENTO) GROUP BY CODSET
SELECT NOMFUN,NOMSET FROM FUNCIONARIO NATURAL JOIN SETOR ORDER BY NOMSET
SELECT NOMFUN,DESCAR FROM FUNCIONARIO NATURAL JOIN CARGO ORDER BY DESCAR DESC
SELECT NOMFUN,NOMSET,DESCAR FROM CARGO NATURAL JOIN FUNCIONARIO NATURAL JOIN SETOR WHERE CODFUN IN(SELECT CODFUN FROM LANCAMENTO)
SELECT NOMFUN,NOMSET,DESCAR FROM CARGO NATURAL JOIN FUNCIONARIO NATURAL JOIN SETOR WHERE CODFUN NOT IN(SELECT CODFUN FROM LANCAMENTO) AND TO_CHAR(DTNASC,'DD/MM/YYYY') BETWEEN '01/01/2018' AND TO_CHAR(SYSDATE,'DD/MM/YYYY');
SELECT DISTINCT NOMSET FROM SETOR NATURAL JOIN FUNCIONARIO NATURAL JOIN LANCAMENTO
SELECT DISTINCT DESCAR FROM CARGO NATURAL JOIN FUNCIONARIO NATURAL JOIN LANCAMENTO
SELECT NOMFUN FROM FUNCIONARIO NATURAL JOIN LANCAMENTO WHERE CODLAN = CODFUN
SELECT DISTINCT NOMFUN,DESCAR,NOMSET FROM FUNCIONARIO FULL OUTER JOIN LANCAMENTO L ON FUNCIONARIO.CODFUN = L.CODFUN JOIN CARGO C2 ON FUNCIONARIO.CODCAR = C2.CODCAR JOIN SETOR S ON FUNCIONARIO.CODSET = S.CODSET